version: '3.8'



services:

      frontend:

        image: frontend:latest

        ports:

          - 5000:5000



      backend:

        image: backend:latest

        ports:

          - 8080:8080

# not sure if the point of this exercise was to deploy both machines without existing images. I used the sme images that I made in front/backend part.
